### ISSUE TITLE
use of sub keys causes problems with git-crypt add-gpg-user

### ISSUE THREAD

**Issue by dupuy** [AGWA/git-crypt#49] opened 2015-03-27 16:35 UTC
With a key fingerprint list like the following:
```
uid:-::::1380542123::483DC941B99712E796FEB92806DB709EF656D817::Adam Langley <agl@imperialviolet.org>:
sub:-:4096:1:F5ED32359DF91734:1380542123:1538222123:::::a:
fpr:::::::::8DD5BE5596D69B9858AEBEB3F5ED32359DF91734:
sub:e:4096:1:B91FE4A53C9B219E:1380839607:1412375607:::::e:
fpr:::::::::D6605535A1B8BF9C72ABAB7EB91FE4A53C9B219E:
pub:-:4096:1:8E274100D395EB04:1408454497:1723814497::-:::scaESCA:
fpr:::::::::33C4CC1525CB0B47AD03CE278E274100D395EB04:
```
the multiple fpr lines for the sub keys cause git-crypt add-gpg-user to fail with "Error: more than one public key matches 'B91FE4A53C9B219E' - please be more specific"

The (sub)key with 'e' (encrypt) capability should be selected.

**Comment by AGWA** [comment] 2015-03-27 16:53
I've never seen `fpr` lines output after each subkey before - only after public keys.  What version of GnuPG is this?  Do you have any `list-options` set in your gpg.conf?

**Comment by AGWA** [comment] 2015-03-27 17:01
Another anomaly with that output is that 33C4CC1525CB0B47AD03CE278E274100D395EB04 isn't AGL's fingerprint.  And it's not on the public key servers.

Could you send me the output of `gpg --batch --with-colons --fingerprint --list-keys B91FE4A53C9B219E`?

**Comment by dupuy** [comment] 2015-03-27 17:39
This is the MacOS GPGTools / MacGPG version (I might also have a homebrew one installed, but I'm not using it);
```
$ gpg --version
gpg (GnuPG/MacGPG2) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ?, ?
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

There are some `list-options` set up by default (I may have tweaked them a bit):
```
$ egrep -v '^(#|group)' ~/.gnupg/gpg.conf | grep .
default-key BBE8C56A9FCB1F819C799D7B208B8A8BEC87905D
require-cross-certification
charset utf-8
keyid-format 0xlong
with-fingerprint
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP
keyserver hkp://pool.sks-keyservers.net
keyserver-options auto-key-retrieve
keyserver-options no-honor-keyserver-url
keyserver-options ca-cert-file=/Users/dupuy/.gnupg/sks-keyservers.netCA.pem
auto-key-locate cert pka ldap hkp://keys.gnupg.net
comment GPGTools - http://gpgtools.org
no-emit-version
```

The AGL sig might have been a separate code-signing key I pulled from Pond, anyhow, here is the output I get for your gpg command:
```
$ gpg --batch --with-colons --fingerprint --list-keys B91FE4A53C9B219E
sub:-:4096:1:F5ED32359DF91734:1380542123:1538222123:::::a:
fpr:::::::::8DD5BE5596D69B9858AEBEB3F5ED32359DF91734:
sub:e:4096:1:B91FE4A53C9B219E:1380839607:1412375607:::::e:
fpr:::::::::D6605535A1B8BF9C72ABAB7EB91FE4A53C9B219E:
```

**Comment by AGWA** [comment] 2015-03-30 19:09
It looks like your `with-fingerprint` option is doing this.  It is extremely annoying that the output of `--with-colons`, which is intended for machine parsing, is affected by options in the user's gpg.conf.  This makes GPG practically un-scriptable.

I guess I'll change git-crypt to only care about `fpr` lines following a `pub` line, and wait until the next bug report caused by a user's GPG config.

**Comment by AGWA** [comment] 2015-04-01 03:26
This has been fixed by ad71c7ffaeb96107ad3dfa59af2b93da248fb257.  I will probably release a new version of git-crypt soon.  Thanks for reporting this!

**Closed by AGWA** 2015-04-01 03:26 UTC

**Comment by dupuy** [comment] 2015-04-07 10:37
Thanks for your debugging of the problem - as it turned out, my workaround was not functional, since it caused me to select the encryption subkey, which was *not* the right key to select.  I commented out the `with-fingerprint` option in my GPG settings and now when I use `add-gpg-user` the commit shows the user's full name and e-mail, and even more important, actually allows the other person to unlock the repository.

**Comment by AGWA** [comment] 2015-04-07 16:20
Did you have a chance to try git-crypt with the latest commits?  That should allow you to use `add-gpg-user` even if `with-fingerprint` is enabled in your GPG config.
